// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: wechaty/puppet/friendship.proto

package puppet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendshipType int32

const (
	FriendshipType_FRIENDSHIP_TYPE_UNSPECIFIED FriendshipType = 0
	FriendshipType_FRIENDSHIP_TYPE_CONFIRM     FriendshipType = 1
	FriendshipType_FRIENDSHIP_TYPE_RECEIVE     FriendshipType = 2
	FriendshipType_FRIENDSHIP_TYPE_VERIFY      FriendshipType = 3
)

// Enum value maps for FriendshipType.
var (
	FriendshipType_name = map[int32]string{
		0: "FRIENDSHIP_TYPE_UNSPECIFIED",
		1: "FRIENDSHIP_TYPE_CONFIRM",
		2: "FRIENDSHIP_TYPE_RECEIVE",
		3: "FRIENDSHIP_TYPE_VERIFY",
	}
	FriendshipType_value = map[string]int32{
		"FRIENDSHIP_TYPE_UNSPECIFIED": 0,
		"FRIENDSHIP_TYPE_CONFIRM":     1,
		"FRIENDSHIP_TYPE_RECEIVE":     2,
		"FRIENDSHIP_TYPE_VERIFY":      3,
	}
)

func (x FriendshipType) Enum() *FriendshipType {
	p := new(FriendshipType)
	*p = x
	return p
}

func (x FriendshipType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendshipType) Descriptor() protoreflect.EnumDescriptor {
	return file_wechaty_puppet_friendship_proto_enumTypes[0].Descriptor()
}

func (FriendshipType) Type() protoreflect.EnumType {
	return &file_wechaty_puppet_friendship_proto_enumTypes[0]
}

func (x FriendshipType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendshipType.Descriptor instead.
func (FriendshipType) EnumDescriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{0}
}

type FriendshipSceneType int32

const (
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_UNSPECIFIED FriendshipSceneType = 0
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_QQ          FriendshipSceneType = 1
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_EMAIL       FriendshipSceneType = 2
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_WEIXIN      FriendshipSceneType = 3
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_QQTBD       FriendshipSceneType = 12
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_ROOM        FriendshipSceneType = 14
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_PHONE       FriendshipSceneType = 15
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_CARD        FriendshipSceneType = 17
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_LOCATION    FriendshipSceneType = 18
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_BOTTLE      FriendshipSceneType = 25
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_SHAKING     FriendshipSceneType = 29
	FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_QRCODE      FriendshipSceneType = 30
)

// Enum value maps for FriendshipSceneType.
var (
	FriendshipSceneType_name = map[int32]string{
		0:  "FRIENDSHIP_SCENE_TYPE_UNSPECIFIED",
		1:  "FRIENDSHIP_SCENE_TYPE_QQ",
		2:  "FRIENDSHIP_SCENE_TYPE_EMAIL",
		3:  "FRIENDSHIP_SCENE_TYPE_WEIXIN",
		12: "FRIENDSHIP_SCENE_TYPE_QQTBD",
		14: "FRIENDSHIP_SCENE_TYPE_ROOM",
		15: "FRIENDSHIP_SCENE_TYPE_PHONE",
		17: "FRIENDSHIP_SCENE_TYPE_CARD",
		18: "FRIENDSHIP_SCENE_TYPE_LOCATION",
		25: "FRIENDSHIP_SCENE_TYPE_BOTTLE",
		29: "FRIENDSHIP_SCENE_TYPE_SHAKING",
		30: "FRIENDSHIP_SCENE_TYPE_QRCODE",
	}
	FriendshipSceneType_value = map[string]int32{
		"FRIENDSHIP_SCENE_TYPE_UNSPECIFIED": 0,
		"FRIENDSHIP_SCENE_TYPE_QQ":          1,
		"FRIENDSHIP_SCENE_TYPE_EMAIL":       2,
		"FRIENDSHIP_SCENE_TYPE_WEIXIN":      3,
		"FRIENDSHIP_SCENE_TYPE_QQTBD":       12,
		"FRIENDSHIP_SCENE_TYPE_ROOM":        14,
		"FRIENDSHIP_SCENE_TYPE_PHONE":       15,
		"FRIENDSHIP_SCENE_TYPE_CARD":        17,
		"FRIENDSHIP_SCENE_TYPE_LOCATION":    18,
		"FRIENDSHIP_SCENE_TYPE_BOTTLE":      25,
		"FRIENDSHIP_SCENE_TYPE_SHAKING":     29,
		"FRIENDSHIP_SCENE_TYPE_QRCODE":      30,
	}
)

func (x FriendshipSceneType) Enum() *FriendshipSceneType {
	p := new(FriendshipSceneType)
	*p = x
	return p
}

func (x FriendshipSceneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendshipSceneType) Descriptor() protoreflect.EnumDescriptor {
	return file_wechaty_puppet_friendship_proto_enumTypes[1].Descriptor()
}

func (FriendshipSceneType) Type() protoreflect.EnumType {
	return &file_wechaty_puppet_friendship_proto_enumTypes[1]
}

func (x FriendshipSceneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendshipSceneType.Descriptor instead.
func (FriendshipSceneType) EnumDescriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{1}
}

type FriendshipPayloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//*
	// Huan(202003):
	//  What's the reason we need belowing payload?
	//  We should remove it if possible.
	//
	// Deprecated: Do not use.
	PayloadStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=payload_string_value_deprecated,json=payloadStringValueDeprecated,proto3" json:"payload_string_value_deprecated,omitempty"` // DEPRECATED, will be removed after Dec 31, 2022
	Payload                      string                  `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *FriendshipPayloadRequest) Reset() {
	*x = FriendshipPayloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_friendship_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendshipPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipPayloadRequest) ProtoMessage() {}

func (x *FriendshipPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_friendship_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipPayloadRequest.ProtoReflect.Descriptor instead.
func (*FriendshipPayloadRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{0}
}

func (x *FriendshipPayloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Deprecated: Do not use.
func (x *FriendshipPayloadRequest) GetPayloadStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.PayloadStringValueDeprecated
	}
	return nil
}

func (x *FriendshipPayloadRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type FriendshipPayloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId string              `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Hello     string              `protobuf:"bytes,3,opt,name=hello,proto3" json:"hello,omitempty"`
	Type      FriendshipType      `protobuf:"varint,4,opt,name=type,proto3,enum=wechaty.puppet.FriendshipType" json:"type,omitempty"`
	Stranger  string              `protobuf:"bytes,5,opt,name=stranger,proto3" json:"stranger,omitempty"`
	Ticket    string              `protobuf:"bytes,6,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Scene     FriendshipSceneType `protobuf:"varint,7,opt,name=scene,proto3,enum=wechaty.puppet.FriendshipSceneType" json:"scene,omitempty"`
}

func (x *FriendshipPayloadResponse) Reset() {
	*x = FriendshipPayloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_friendship_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendshipPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipPayloadResponse) ProtoMessage() {}

func (x *FriendshipPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_friendship_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipPayloadResponse.ProtoReflect.Descriptor instead.
func (*FriendshipPayloadResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{1}
}

func (x *FriendshipPayloadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FriendshipPayloadResponse) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *FriendshipPayloadResponse) GetHello() string {
	if x != nil {
		return x.Hello
	}
	return ""
}

func (x *FriendshipPayloadResponse) GetType() FriendshipType {
	if x != nil {
		return x.Type
	}
	return FriendshipType_FRIENDSHIP_TYPE_UNSPECIFIED
}

func (x *FriendshipPayloadResponse) GetStranger() string {
	if x != nil {
		return x.Stranger
	}
	return ""
}

func (x *FriendshipPayloadResponse) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *FriendshipPayloadResponse) GetScene() FriendshipSceneType {
	if x != nil {
		return x.Scene
	}
	return FriendshipSceneType_FRIENDSHIP_SCENE_TYPE_UNSPECIFIED
}

type FriendshipSearchPhoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *FriendshipSearchPhoneRequest) Reset() {
	*x = FriendshipSearchPhoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_friendship_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendshipSearchPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipSearchPhoneRequest) ProtoMessage() {}

func (x *FriendshipSearchPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_friendship_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipSearchPhoneRequest.ProtoReflect.Descriptor instead.
func (*FriendshipSearchPhoneRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{2}
}

func (x *FriendshipSearchPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type FriendshipSearchPhoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// nullable
	//
	// Deprecated: Do not use.
	ContactIdStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=contact_id_string_value_deprecated,json=contactIdStringValueDeprecated,proto3" json:"contact_id_string_value_deprecated,omitempty"` // DEPRECATED, will be removed after Dec 31, 2022
	ContactId                      string                  `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
}

func (x *FriendshipSearchPhoneResponse) Reset() {
	*x = FriendshipSearchPhoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_friendship_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendshipSearchPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipSearchPhoneResponse) ProtoMessage() {}

func (x *FriendshipSearchPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_friendship_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipSearchPhoneResponse.ProtoReflect.Descriptor instead.
func (*FriendshipSearchPhoneResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{3}
}

// Deprecated: Do not use.
func (x *FriendshipSearchPhoneResponse) GetContactIdStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.ContactIdStringValueDeprecated
	}
	return nil
}

func (x *FriendshipSearchPhoneResponse) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

//*
// Huan(202003): we just rename the payload message because gRPC only care about the message structure
//  (and as long as we keep consistent with the old structure).
//
//  @link https://github.com/wechaty/grpc/pull/173
//
// Rename:
//  1. `FriendshipSearchWeixinRequest`    -> `FriendshipSearchHandleRequest`
//  2. `FriendshipSearchWeixinReqsponse`  -> `FriendshipSearchHandleResponse`
type FriendshipSearchHandleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// Huan(202203): in gRPC, we can freely rename the field name as long as the number keep consistent.
	//  so we can just rename `weixin` to `handle` here.
	//
	// (Huan(20220329): use `weixin` for now, until we upgrade to v2.0
	//  the `wechaty-grpc@1.0.0` will use the latest v1.x automatically when running `npm install`
	//    which will causing a breaking change.
	//  @link https://github.com/wechaty/getting-started/issues/254
	//
	// TODO: rename `weixin` to `handle` in v2.0.0
	Weixin string `protobuf:"bytes,1,opt,name=weixin,proto3" json:"weixin,omitempty"`
}

func (x *FriendshipSearchHandleRequest) Reset() {
	*x = FriendshipSearchHandleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_friendship_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendshipSearchHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipSearchHandleRequest) ProtoMessage() {}

func (x *FriendshipSearchHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_friendship_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipSearchHandleRequest.ProtoReflect.Descriptor instead.
func (*FriendshipSearchHandleRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{4}
}

func (x *FriendshipSearchHandleRequest) GetWeixin() string {
	if x != nil {
		return x.Weixin
	}
	return ""
}

type FriendshipSearchHandleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// nullable
	//
	// Deprecated: Do not use.
	ContactIdStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=contact_id_string_value_deprecated,json=contactIdStringValueDeprecated,proto3" json:"contact_id_string_value_deprecated,omitempty"` // DEPRECATED, will be removed after Dec 31, 2022
	ContactId                      string                  `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
}

func (x *FriendshipSearchHandleResponse) Reset() {
	*x = FriendshipSearchHandleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_friendship_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendshipSearchHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipSearchHandleResponse) ProtoMessage() {}

func (x *FriendshipSearchHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_friendship_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipSearchHandleResponse.ProtoReflect.Descriptor instead.
func (*FriendshipSearchHandleResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{5}
}

// Deprecated: Do not use.
func (x *FriendshipSearchHandleResponse) GetContactIdStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.ContactIdStringValueDeprecated
	}
	return nil
}

func (x *FriendshipSearchHandleResponse) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

type FriendshipAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContactId string `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Hello     string `protobuf:"bytes,2,opt,name=hello,proto3" json:"hello,omitempty"`
	// Deprecated: Do not use.
	SourceRoomIdStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=source_room_id_string_value_deprecated,json=sourceRoomIdStringValueDeprecated,proto3" json:"source_room_id_string_value_deprecated,omitempty"` // Deprecated: will be removed after Dec 31, 2022
	// Deprecated: Do not use.
	SourceContactIdStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=source_contact_id_string_value_deprecated,json=sourceContactIdStringValueDeprecated,proto3" json:"source_contact_id_string_value_deprecated,omitempty"` // Deprecated: will be removed after Dec 31, 2022
	Referrer                             *Referrer               `protobuf:"bytes,5,opt,name=referrer,proto3" json:"referrer,omitempty"`
}

func (x *FriendshipAddRequest) Reset() {
	*x = FriendshipAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_friendship_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendshipAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipAddRequest) ProtoMessage() {}

func (x *FriendshipAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_friendship_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipAddRequest.ProtoReflect.Descriptor instead.
func (*FriendshipAddRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{6}
}

func (x *FriendshipAddRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *FriendshipAddRequest) GetHello() string {
	if x != nil {
		return x.Hello
	}
	return ""
}

// Deprecated: Do not use.
func (x *FriendshipAddRequest) GetSourceRoomIdStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.SourceRoomIdStringValueDeprecated
	}
	return nil
}

// Deprecated: Do not use.
func (x *FriendshipAddRequest) GetSourceContactIdStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.SourceContactIdStringValueDeprecated
	}
	return nil
}

func (x *FriendshipAddRequest) GetReferrer() *Referrer {
	if x != nil {
		return x.Referrer
	}
	return nil
}

type FriendshipAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FriendshipAddResponse) Reset() {
	*x = FriendshipAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_friendship_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendshipAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipAddResponse) ProtoMessage() {}

func (x *FriendshipAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_friendship_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipAddResponse.ProtoReflect.Descriptor instead.
func (*FriendshipAddResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{7}
}

type FriendshipAcceptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FriendshipAcceptRequest) Reset() {
	*x = FriendshipAcceptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_friendship_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendshipAcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipAcceptRequest) ProtoMessage() {}

func (x *FriendshipAcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_friendship_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipAcceptRequest.ProtoReflect.Descriptor instead.
func (*FriendshipAcceptRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{8}
}

func (x *FriendshipAcceptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FriendshipAcceptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FriendshipAcceptResponse) Reset() {
	*x = FriendshipAcceptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_friendship_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendshipAcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipAcceptResponse) ProtoMessage() {}

func (x *FriendshipAcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_friendship_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipAcceptResponse.ProtoReflect.Descriptor instead.
func (*FriendshipAcceptResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_friendship_proto_rawDescGZIP(), []int{9}
}

var File_wechaty_puppet_friendship_proto protoreflect.FileDescriptor

var file_wechaty_puppet_friendship_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2f, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74,
	0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65,
	0x74, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1d, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2f, 0x70, 0x75, 0x70, 0x70, 0x65,
	0x74, 0x2f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xad, 0x01, 0x0a, 0x18, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x67, 0x0a,
	0x1f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x02, 0x18, 0x01, 0x52, 0x1c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x65, 0x70, 0x72,
	0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x83, 0x02, 0x0a, 0x19, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1e, 0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x70, 0x75, 0x70, 0x70,
	0x65, 0x74, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x39, 0x0a, 0x05, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x77, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x79, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x2e, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x22, 0x34, 0x0a, 0x1c, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x73, 0x68, 0x69, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0xac, 0x01, 0x0a,
	0x1d, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c,
	0x0a, 0x22, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x02, 0x18, 0x01, 0x52, 0x1e, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x1d, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x65,
	0x69, 0x78, 0x69, 0x6e, 0x22, 0xad, 0x01, 0x0a, 0x1e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73,
	0x68, 0x69, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c, 0x0a, 0x22, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x02, 0x18, 0x01, 0x52, 0x1e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x64,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x65, 0x70, 0x72, 0x65,
	0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x49, 0x64, 0x22, 0xf1, 0x02, 0x0a, 0x14, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73,
	0x68, 0x69, 0x70, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x12, 0x73, 0x0a, 0x26, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x42, 0x02, 0x18, 0x01, 0x52, 0x21, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x65, 0x70,
	0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x79, 0x0a, 0x29, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x02, 0x18, 0x01, 0x52, 0x24, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x64, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x70,
	0x75, 0x70, 0x70, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x52, 0x08,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x29, 0x0a, 0x17, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x18,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x87, 0x01, 0x0a, 0x0e, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x1b, 0x46,
	0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17,
	0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x43, 0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x46, 0x52, 0x49,
	0x45, 0x4e, 0x44, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x43,
	0x45, 0x49, 0x56, 0x45, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44,
	0x53, 0x48, 0x49, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x56, 0x45, 0x52, 0x49, 0x46, 0x59,
	0x10, 0x03, 0x2a, 0xaa, 0x03, 0x0a, 0x13, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69,
	0x70, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x21, 0x46, 0x52,
	0x49, 0x45, 0x4e, 0x44, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1c, 0x0a, 0x18, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x48, 0x49, 0x50, 0x5f,
	0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x51, 0x51, 0x10, 0x01, 0x12,
	0x1f, 0x0a, 0x1b, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x53, 0x43,
	0x45, 0x4e, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x02,
	0x12, 0x20, 0x0a, 0x1c, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x53,
	0x43, 0x45, 0x4e, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x57, 0x45, 0x49, 0x58, 0x49, 0x4e,
	0x10, 0x03, 0x12, 0x1f, 0x0a, 0x1b, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x48, 0x49, 0x50,
	0x5f, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x51, 0x51, 0x54, 0x42,
	0x44, 0x10, 0x0c, 0x12, 0x1e, 0x0a, 0x1a, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x48, 0x49,
	0x50, 0x5f, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x4f, 0x4f,
	0x4d, 0x10, 0x0e, 0x12, 0x1f, 0x0a, 0x1b, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x48, 0x49,
	0x50, 0x5f, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x48, 0x4f,
	0x4e, 0x45, 0x10, 0x0f, 0x12, 0x1e, 0x0a, 0x1a, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x48,
	0x49, 0x50, 0x5f, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x41,
	0x52, 0x44, 0x10, 0x11, 0x12, 0x22, 0x0a, 0x1e, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x48,
	0x49, 0x50, 0x5f, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x4f,
	0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x12, 0x12, 0x20, 0x0a, 0x1c, 0x46, 0x52, 0x49, 0x45,
	0x4e, 0x44, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x42, 0x4f, 0x54, 0x54, 0x4c, 0x45, 0x10, 0x19, 0x12, 0x21, 0x0a, 0x1d, 0x46, 0x52,
	0x49, 0x45, 0x4e, 0x44, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x53, 0x48, 0x41, 0x4b, 0x49, 0x4e, 0x47, 0x10, 0x1d, 0x12, 0x20, 0x0a,
	0x1c, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x53, 0x43, 0x45, 0x4e,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x51, 0x52, 0x43, 0x4f, 0x44, 0x45, 0x10, 0x1e, 0x42,
	0x67, 0x0a, 0x1d, 0x69, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x77, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74,
	0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x79, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x79, 0x2f, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0xaa, 0x02, 0x1a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wechaty_puppet_friendship_proto_rawDescOnce sync.Once
	file_wechaty_puppet_friendship_proto_rawDescData = file_wechaty_puppet_friendship_proto_rawDesc
)

func file_wechaty_puppet_friendship_proto_rawDescGZIP() []byte {
	file_wechaty_puppet_friendship_proto_rawDescOnce.Do(func() {
		file_wechaty_puppet_friendship_proto_rawDescData = protoimpl.X.CompressGZIP(file_wechaty_puppet_friendship_proto_rawDescData)
	})
	return file_wechaty_puppet_friendship_proto_rawDescData
}

var file_wechaty_puppet_friendship_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wechaty_puppet_friendship_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_wechaty_puppet_friendship_proto_goTypes = []interface{}{
	(FriendshipType)(0),                    // 0: wechaty.puppet.FriendshipType
	(FriendshipSceneType)(0),               // 1: wechaty.puppet.FriendshipSceneType
	(*FriendshipPayloadRequest)(nil),       // 2: wechaty.puppet.FriendshipPayloadRequest
	(*FriendshipPayloadResponse)(nil),      // 3: wechaty.puppet.FriendshipPayloadResponse
	(*FriendshipSearchPhoneRequest)(nil),   // 4: wechaty.puppet.FriendshipSearchPhoneRequest
	(*FriendshipSearchPhoneResponse)(nil),  // 5: wechaty.puppet.FriendshipSearchPhoneResponse
	(*FriendshipSearchHandleRequest)(nil),  // 6: wechaty.puppet.FriendshipSearchHandleRequest
	(*FriendshipSearchHandleResponse)(nil), // 7: wechaty.puppet.FriendshipSearchHandleResponse
	(*FriendshipAddRequest)(nil),           // 8: wechaty.puppet.FriendshipAddRequest
	(*FriendshipAddResponse)(nil),          // 9: wechaty.puppet.FriendshipAddResponse
	(*FriendshipAcceptRequest)(nil),        // 10: wechaty.puppet.FriendshipAcceptRequest
	(*FriendshipAcceptResponse)(nil),       // 11: wechaty.puppet.FriendshipAcceptResponse
	(*wrapperspb.StringValue)(nil),         // 12: google.protobuf.StringValue
	(*Referrer)(nil),                       // 13: wechaty.puppet.Referrer
}
var file_wechaty_puppet_friendship_proto_depIdxs = []int32{
	12, // 0: wechaty.puppet.FriendshipPayloadRequest.payload_string_value_deprecated:type_name -> google.protobuf.StringValue
	0,  // 1: wechaty.puppet.FriendshipPayloadResponse.type:type_name -> wechaty.puppet.FriendshipType
	1,  // 2: wechaty.puppet.FriendshipPayloadResponse.scene:type_name -> wechaty.puppet.FriendshipSceneType
	12, // 3: wechaty.puppet.FriendshipSearchPhoneResponse.contact_id_string_value_deprecated:type_name -> google.protobuf.StringValue
	12, // 4: wechaty.puppet.FriendshipSearchHandleResponse.contact_id_string_value_deprecated:type_name -> google.protobuf.StringValue
	12, // 5: wechaty.puppet.FriendshipAddRequest.source_room_id_string_value_deprecated:type_name -> google.protobuf.StringValue
	12, // 6: wechaty.puppet.FriendshipAddRequest.source_contact_id_string_value_deprecated:type_name -> google.protobuf.StringValue
	13, // 7: wechaty.puppet.FriendshipAddRequest.referrer:type_name -> wechaty.puppet.Referrer
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_wechaty_puppet_friendship_proto_init() }
func file_wechaty_puppet_friendship_proto_init() {
	if File_wechaty_puppet_friendship_proto != nil {
		return
	}
	file_wechaty_puppet_referrer_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_wechaty_puppet_friendship_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendshipPayloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_friendship_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendshipPayloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_friendship_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendshipSearchPhoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_friendship_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendshipSearchPhoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_friendship_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendshipSearchHandleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_friendship_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendshipSearchHandleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_friendship_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendshipAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_friendship_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendshipAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_friendship_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendshipAcceptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_friendship_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendshipAcceptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wechaty_puppet_friendship_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wechaty_puppet_friendship_proto_goTypes,
		DependencyIndexes: file_wechaty_puppet_friendship_proto_depIdxs,
		EnumInfos:         file_wechaty_puppet_friendship_proto_enumTypes,
		MessageInfos:      file_wechaty_puppet_friendship_proto_msgTypes,
	}.Build()
	File_wechaty_puppet_friendship_proto = out.File
	file_wechaty_puppet_friendship_proto_rawDesc = nil
	file_wechaty_puppet_friendship_proto_goTypes = nil
	file_wechaty_puppet_friendship_proto_depIdxs = nil
}
