// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: wechaty/puppet/image.proto

package puppet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageType int32

const (
	ImageType_IMAGE_TYPE_UNSPECIFIED ImageType = 0
	ImageType_IMAGE_TYPE_THUMBNAIL   ImageType = 1
	ImageType_IMAGE_TYPE_HD          ImageType = 2
	ImageType_IMAGE_TYPE_ARTWORK     ImageType = 3
)

// Enum value maps for ImageType.
var (
	ImageType_name = map[int32]string{
		0: "IMAGE_TYPE_UNSPECIFIED",
		1: "IMAGE_TYPE_THUMBNAIL",
		2: "IMAGE_TYPE_HD",
		3: "IMAGE_TYPE_ARTWORK",
	}
	ImageType_value = map[string]int32{
		"IMAGE_TYPE_UNSPECIFIED": 0,
		"IMAGE_TYPE_THUMBNAIL":   1,
		"IMAGE_TYPE_HD":          2,
		"IMAGE_TYPE_ARTWORK":     3,
	}
)

func (x ImageType) Enum() *ImageType {
	p := new(ImageType)
	*p = x
	return p
}

func (x ImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_wechaty_puppet_image_proto_enumTypes[0].Descriptor()
}

func (ImageType) Type() protoreflect.EnumType {
	return &file_wechaty_puppet_image_proto_enumTypes[0]
}

func (x ImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageType.Descriptor instead.
func (ImageType) EnumDescriptor() ([]byte, []int) {
	return file_wechaty_puppet_image_proto_rawDescGZIP(), []int{0}
}

var File_wechaty_puppet_image_proto protoreflect.FileDescriptor

var file_wechaty_puppet_image_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2f, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74,
	0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x77, 0x65,
	0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x2a, 0x6c, 0x0a, 0x09,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x49, 0x4d, 0x41,
	0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x54, 0x48, 0x55, 0x4d, 0x42, 0x4e, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x12,
	0x11, 0x0a, 0x0d, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x48, 0x44,
	0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x41, 0x52, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x03, 0x42, 0x67, 0x0a, 0x1d, 0x69, 0x6f,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x5a, 0x29, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2f,
	0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2f,
	0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0xaa, 0x02, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x75, 0x70,
	0x70, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wechaty_puppet_image_proto_rawDescOnce sync.Once
	file_wechaty_puppet_image_proto_rawDescData = file_wechaty_puppet_image_proto_rawDesc
)

func file_wechaty_puppet_image_proto_rawDescGZIP() []byte {
	file_wechaty_puppet_image_proto_rawDescOnce.Do(func() {
		file_wechaty_puppet_image_proto_rawDescData = protoimpl.X.CompressGZIP(file_wechaty_puppet_image_proto_rawDescData)
	})
	return file_wechaty_puppet_image_proto_rawDescData
}

var file_wechaty_puppet_image_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wechaty_puppet_image_proto_goTypes = []interface{}{
	(ImageType)(0), // 0: wechaty.puppet.ImageType
}
var file_wechaty_puppet_image_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wechaty_puppet_image_proto_init() }
func file_wechaty_puppet_image_proto_init() {
	if File_wechaty_puppet_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wechaty_puppet_image_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wechaty_puppet_image_proto_goTypes,
		DependencyIndexes: file_wechaty_puppet_image_proto_depIdxs,
		EnumInfos:         file_wechaty_puppet_image_proto_enumTypes,
	}.Build()
	File_wechaty_puppet_image_proto = out.File
	file_wechaty_puppet_image_proto_rawDesc = nil
	file_wechaty_puppet_image_proto_goTypes = nil
	file_wechaty_puppet_image_proto_depIdxs = nil
}
