// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: wechaty/puppet/message.proto

package puppet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED  MessageType = 0
	MessageType_MESSAGE_TYPE_ATTACHMENT   MessageType = 1
	MessageType_MESSAGE_TYPE_AUDIO        MessageType = 2
	MessageType_MESSAGE_TYPE_CONTACT      MessageType = 3
	MessageType_MESSAGE_TYPE_EMOTICON     MessageType = 4
	MessageType_MESSAGE_TYPE_IMAGE        MessageType = 5
	MessageType_MESSAGE_TYPE_TEXT         MessageType = 6
	MessageType_MESSAGE_TYPE_VIDEO        MessageType = 7
	MessageType_MESSAGE_TYPE_CHAT_HISTORY MessageType = 8
	MessageType_MESSAGE_TYPE_LOCATION     MessageType = 9
	MessageType_MESSAGE_TYPE_MINI_PROGRAM MessageType = 10
	MessageType_MESSAGE_TYPE_TRANSFER     MessageType = 11
	MessageType_MESSAGE_TYPE_RED_ENVELOPE MessageType = 12
	MessageType_MESSAGE_TYPE_RECALLED     MessageType = 13
	MessageType_MESSAGE_TYPE_URL          MessageType = 14
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNSPECIFIED",
		1:  "MESSAGE_TYPE_ATTACHMENT",
		2:  "MESSAGE_TYPE_AUDIO",
		3:  "MESSAGE_TYPE_CONTACT",
		4:  "MESSAGE_TYPE_EMOTICON",
		5:  "MESSAGE_TYPE_IMAGE",
		6:  "MESSAGE_TYPE_TEXT",
		7:  "MESSAGE_TYPE_VIDEO",
		8:  "MESSAGE_TYPE_CHAT_HISTORY",
		9:  "MESSAGE_TYPE_LOCATION",
		10: "MESSAGE_TYPE_MINI_PROGRAM",
		11: "MESSAGE_TYPE_TRANSFER",
		12: "MESSAGE_TYPE_RED_ENVELOPE",
		13: "MESSAGE_TYPE_RECALLED",
		14: "MESSAGE_TYPE_URL",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":  0,
		"MESSAGE_TYPE_ATTACHMENT":   1,
		"MESSAGE_TYPE_AUDIO":        2,
		"MESSAGE_TYPE_CONTACT":      3,
		"MESSAGE_TYPE_EMOTICON":     4,
		"MESSAGE_TYPE_IMAGE":        5,
		"MESSAGE_TYPE_TEXT":         6,
		"MESSAGE_TYPE_VIDEO":        7,
		"MESSAGE_TYPE_CHAT_HISTORY": 8,
		"MESSAGE_TYPE_LOCATION":     9,
		"MESSAGE_TYPE_MINI_PROGRAM": 10,
		"MESSAGE_TYPE_TRANSFER":     11,
		"MESSAGE_TYPE_RED_ENVELOPE": 12,
		"MESSAGE_TYPE_RECALLED":     13,
		"MESSAGE_TYPE_URL":          14,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_wechaty_puppet_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_wechaty_puppet_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{0}
}

type MessagePayloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessagePayloadRequest) Reset() {
	*x = MessagePayloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePayloadRequest) ProtoMessage() {}

func (x *MessagePayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePayloadRequest.ProtoReflect.Descriptor instead.
func (*MessagePayloadRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessagePayloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessagePayloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Text     string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	//*
	// @deprecated will be removed after Dec 31, 2022
	//  Huan(202109): use receive_time(10) instead
	//
	// Deprecated: Do not use.
	TimestampDeprecated uint64                 `protobuf:"varint,4,opt,name=timestamp_deprecated,json=timestampDeprecated,proto3" json:"timestamp_deprecated,omitempty"`
	Type                MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=wechaty.puppet.MessageType" json:"type,omitempty"`
	TalkerId            string                 `protobuf:"bytes,6,opt,name=talker_id,json=talkerId,proto3" json:"talker_id,omitempty"`
	RoomId              string                 `protobuf:"bytes,7,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ListenerId          string                 `protobuf:"bytes,8,opt,name=listener_id,json=listenerId,proto3" json:"listener_id,omitempty"`
	MentionIds          []string               `protobuf:"bytes,9,rep,name=mention_ids,json=mentionIds,proto3" json:"mention_ids,omitempty"`
	ReceiveTime         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
}

func (x *MessagePayloadResponse) Reset() {
	*x = MessagePayloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePayloadResponse) ProtoMessage() {}

func (x *MessagePayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePayloadResponse.ProtoReflect.Descriptor instead.
func (*MessagePayloadResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessagePayloadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessagePayloadResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MessagePayloadResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Deprecated: Do not use.
func (x *MessagePayloadResponse) GetTimestampDeprecated() uint64 {
	if x != nil {
		return x.TimestampDeprecated
	}
	return 0
}

func (x *MessagePayloadResponse) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *MessagePayloadResponse) GetTalkerId() string {
	if x != nil {
		return x.TalkerId
	}
	return ""
}

func (x *MessagePayloadResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessagePayloadResponse) GetListenerId() string {
	if x != nil {
		return x.ListenerId
	}
	return ""
}

func (x *MessagePayloadResponse) GetMentionIds() []string {
	if x != nil {
		return x.MentionIds
	}
	return nil
}

func (x *MessagePayloadResponse) GetReceiveTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceiveTime
	}
	return nil
}

type MessageImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type ImageType `protobuf:"varint,2,opt,name=type,proto3,enum=wechaty.puppet.ImageType" json:"type,omitempty"`
}

func (x *MessageImageRequest) Reset() {
	*x = MessageImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageImageRequest) ProtoMessage() {}

func (x *MessageImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageImageRequest.ProtoReflect.Descriptor instead.
func (*MessageImageRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{2}
}

func (x *MessageImageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageImageRequest) GetType() ImageType {
	if x != nil {
		return x.Type
	}
	return ImageType_IMAGE_TYPE_UNSPECIFIED
}

type MessageImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileBox string `protobuf:"bytes,1,opt,name=file_box,json=fileBox,proto3" json:"file_box,omitempty"`
}

func (x *MessageImageResponse) Reset() {
	*x = MessageImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageImageResponse) ProtoMessage() {}

func (x *MessageImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageImageResponse.ProtoReflect.Descriptor instead.
func (*MessageImageResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{3}
}

func (x *MessageImageResponse) GetFileBox() string {
	if x != nil {
		return x.FileBox
	}
	return ""
}

type MessageContactRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageContactRequest) Reset() {
	*x = MessageContactRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContactRequest) ProtoMessage() {}

func (x *MessageContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContactRequest.ProtoReflect.Descriptor instead.
func (*MessageContactRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{4}
}

func (x *MessageContactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageContactResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageContactResponse) Reset() {
	*x = MessageContactResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContactResponse) ProtoMessage() {}

func (x *MessageContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContactResponse.ProtoReflect.Descriptor instead.
func (*MessageContactResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{5}
}

func (x *MessageContactResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageFileRequest) Reset() {
	*x = MessageFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFileRequest) ProtoMessage() {}

func (x *MessageFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFileRequest.ProtoReflect.Descriptor instead.
func (*MessageFileRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{6}
}

func (x *MessageFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileBox string `protobuf:"bytes,1,opt,name=file_box,json=fileBox,proto3" json:"file_box,omitempty"`
}

func (x *MessageFileResponse) Reset() {
	*x = MessageFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFileResponse) ProtoMessage() {}

func (x *MessageFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFileResponse.ProtoReflect.Descriptor instead.
func (*MessageFileResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{7}
}

func (x *MessageFileResponse) GetFileBox() string {
	if x != nil {
		return x.FileBox
	}
	return ""
}

type MessageMiniProgramRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageMiniProgramRequest) Reset() {
	*x = MessageMiniProgramRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageMiniProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMiniProgramRequest) ProtoMessage() {}

func (x *MessageMiniProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMiniProgramRequest.ProtoReflect.Descriptor instead.
func (*MessageMiniProgramRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{8}
}

func (x *MessageMiniProgramRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageMiniProgramResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// Huan(202110): We should use payload instead of JSON.stringify string
	//  The compatible code will be removed after Dec 31, 2022
	//
	// Deprecated: Do not use.
	MiniProgramDeprecated string              `protobuf:"bytes,1,opt,name=mini_program_deprecated,json=miniProgramDeprecated,proto3" json:"mini_program_deprecated,omitempty"` // deprecated after Sep 31, 2021, remove compatible code after Dec 31, 2022
	MiniProgram           *MiniProgramPayload `protobuf:"bytes,2,opt,name=mini_program,json=miniProgram,proto3" json:"mini_program,omitempty"`
}

func (x *MessageMiniProgramResponse) Reset() {
	*x = MessageMiniProgramResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageMiniProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMiniProgramResponse) ProtoMessage() {}

func (x *MessageMiniProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMiniProgramResponse.ProtoReflect.Descriptor instead.
func (*MessageMiniProgramResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{9}
}

// Deprecated: Do not use.
func (x *MessageMiniProgramResponse) GetMiniProgramDeprecated() string {
	if x != nil {
		return x.MiniProgramDeprecated
	}
	return ""
}

func (x *MessageMiniProgramResponse) GetMiniProgram() *MiniProgramPayload {
	if x != nil {
		return x.MiniProgram
	}
	return nil
}

type MessageUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageUrlRequest) Reset() {
	*x = MessageUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUrlRequest) ProtoMessage() {}

func (x *MessageUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUrlRequest.ProtoReflect.Descriptor instead.
func (*MessageUrlRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{10}
}

func (x *MessageUrlRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// Huan(202110): We should use payload instead of JSON.stringify string
	//  The compatible code will be removed after Dec 31, 2022
	//
	// Deprecated: Do not use.
	UrlLinkDeprecated string          `protobuf:"bytes,1,opt,name=url_link_deprecated,json=urlLinkDeprecated,proto3" json:"url_link_deprecated,omitempty"` // deprecated after Sep 31, 2021, remove compatible code after Dec 31, 2022
	UrlLink           *UrlLinkPayload `protobuf:"bytes,2,opt,name=url_link,json=urlLink,proto3" json:"url_link,omitempty"`
}

func (x *MessageUrlResponse) Reset() {
	*x = MessageUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUrlResponse) ProtoMessage() {}

func (x *MessageUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUrlResponse.ProtoReflect.Descriptor instead.
func (*MessageUrlResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{11}
}

// Deprecated: Do not use.
func (x *MessageUrlResponse) GetUrlLinkDeprecated() string {
	if x != nil {
		return x.UrlLinkDeprecated
	}
	return ""
}

func (x *MessageUrlResponse) GetUrlLink() *UrlLinkPayload {
	if x != nil {
		return x.UrlLink
	}
	return nil
}

type MessageSendContactRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ContactId      string `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
}

func (x *MessageSendContactRequest) Reset() {
	*x = MessageSendContactRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendContactRequest) ProtoMessage() {}

func (x *MessageSendContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendContactRequest.ProtoReflect.Descriptor instead.
func (*MessageSendContactRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{12}
}

func (x *MessageSendContactRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageSendContactRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

type MessageSendContactResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// @deprecated:
	//  Huan(202109): Wrapper types must not be used going forward.
	//    https://cloud.google.com/apis/design/design_patterns#optional_primitive_fields
	//
	// Deprecated: Do not use.
	IdStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id_string_value_deprecated,json=idStringValueDeprecated,proto3" json:"id_string_value_deprecated,omitempty"` // Deprecated after Sep 31, 2021, will be removed after Dec 31, 2022
	Id                      string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageSendContactResponse) Reset() {
	*x = MessageSendContactResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendContactResponse) ProtoMessage() {}

func (x *MessageSendContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendContactResponse.ProtoReflect.Descriptor instead.
func (*MessageSendContactResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{13}
}

// Deprecated: Do not use.
func (x *MessageSendContactResponse) GetIdStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.IdStringValueDeprecated
	}
	return nil
}

func (x *MessageSendContactResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageSendFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	FileBox        string `protobuf:"bytes,2,opt,name=file_box,json=fileBox,proto3" json:"file_box,omitempty"`
}

func (x *MessageSendFileRequest) Reset() {
	*x = MessageSendFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendFileRequest) ProtoMessage() {}

func (x *MessageSendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendFileRequest.ProtoReflect.Descriptor instead.
func (*MessageSendFileRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{14}
}

func (x *MessageSendFileRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageSendFileRequest) GetFileBox() string {
	if x != nil {
		return x.FileBox
	}
	return ""
}

type MessageSendFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// @deprecated:
	//  Huan(202109): Wrapper types must not be used going forward.
	//    https://cloud.google.com/apis/design/design_patterns#optional_primitive_fields
	//
	// Deprecated: Do not use.
	IdStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id_string_value_deprecated,json=idStringValueDeprecated,proto3" json:"id_string_value_deprecated,omitempty"` // Deprecated after Sep 31, 2021, will be removed after Dec 31, 2022
	Id                      string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageSendFileResponse) Reset() {
	*x = MessageSendFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendFileResponse) ProtoMessage() {}

func (x *MessageSendFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendFileResponse.ProtoReflect.Descriptor instead.
func (*MessageSendFileResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{15}
}

// Deprecated: Do not use.
func (x *MessageSendFileResponse) GetIdStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.IdStringValueDeprecated
	}
	return nil
}

func (x *MessageSendFileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageSendTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Text           string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Huan(202011) FIXME: Issue #99
	// https://github.com/wechaty/grpc/issues/99
	MentionalIds []string `protobuf:"bytes,3,rep,name=mentional_ids,json=mentionalIds,proto3" json:"mentional_ids,omitempty"`
}

func (x *MessageSendTextRequest) Reset() {
	*x = MessageSendTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendTextRequest) ProtoMessage() {}

func (x *MessageSendTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendTextRequest.ProtoReflect.Descriptor instead.
func (*MessageSendTextRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{16}
}

func (x *MessageSendTextRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageSendTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageSendTextRequest) GetMentionalIds() []string {
	if x != nil {
		return x.MentionalIds
	}
	return nil
}

type MessageSendTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// @deprecated:
	//  Huan(202109): Wrapper types must not be used going forward.
	//    https://cloud.google.com/apis/design/design_patterns#optional_primitive_fields
	//
	// Deprecated: Do not use.
	IdStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id_string_value_deprecated,json=idStringValueDeprecated,proto3" json:"id_string_value_deprecated,omitempty"` // Deprecated after Sep 31, 2021, will be removed after Dec 31, 2022
	Id                      string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageSendTextResponse) Reset() {
	*x = MessageSendTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendTextResponse) ProtoMessage() {}

func (x *MessageSendTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendTextResponse.ProtoReflect.Descriptor instead.
func (*MessageSendTextResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{17}
}

// Deprecated: Do not use.
func (x *MessageSendTextResponse) GetIdStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.IdStringValueDeprecated
	}
	return nil
}

func (x *MessageSendTextResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageSendMiniProgramRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	//*
	// Huan(202110): We should use payload instead of JSON.stringify string
	//  The compatible code will be removed after Dec 31, 2022
	//
	// Deprecated: Do not use.
	MiniProgramDeprecated string              `protobuf:"bytes,2,opt,name=mini_program_deprecated,json=miniProgramDeprecated,proto3" json:"mini_program_deprecated,omitempty"` // deprecated after Sep 31, 2021, remove compatible code after Dec 31, 2022
	MiniProgram           *MiniProgramPayload `protobuf:"bytes,3,opt,name=mini_program,json=miniProgram,proto3" json:"mini_program,omitempty"`
}

func (x *MessageSendMiniProgramRequest) Reset() {
	*x = MessageSendMiniProgramRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendMiniProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendMiniProgramRequest) ProtoMessage() {}

func (x *MessageSendMiniProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendMiniProgramRequest.ProtoReflect.Descriptor instead.
func (*MessageSendMiniProgramRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{18}
}

func (x *MessageSendMiniProgramRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// Deprecated: Do not use.
func (x *MessageSendMiniProgramRequest) GetMiniProgramDeprecated() string {
	if x != nil {
		return x.MiniProgramDeprecated
	}
	return ""
}

func (x *MessageSendMiniProgramRequest) GetMiniProgram() *MiniProgramPayload {
	if x != nil {
		return x.MiniProgram
	}
	return nil
}

type MessageSendMiniProgramResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// @deprecated:
	//  Huan(202109): Wrapper types must not be used going forward.
	//    https://cloud.google.com/apis/design/design_patterns#optional_primitive_fields
	//
	// Deprecated: Do not use.
	IdStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id_string_value_deprecated,json=idStringValueDeprecated,proto3" json:"id_string_value_deprecated,omitempty"` // Deprecated after Sep 31, 2021, will be removed after Dec 31, 2022
	Id                      string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageSendMiniProgramResponse) Reset() {
	*x = MessageSendMiniProgramResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendMiniProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendMiniProgramResponse) ProtoMessage() {}

func (x *MessageSendMiniProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendMiniProgramResponse.ProtoReflect.Descriptor instead.
func (*MessageSendMiniProgramResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{19}
}

// Deprecated: Do not use.
func (x *MessageSendMiniProgramResponse) GetIdStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.IdStringValueDeprecated
	}
	return nil
}

func (x *MessageSendMiniProgramResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageSendUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	//*
	// Huan(202110): We should use payload instead of JSON.stringify string
	//  The compatible code will be removed after Dec 31, 2022
	//
	// Deprecated: Do not use.
	UrlLinkDeprecated string          `protobuf:"bytes,2,opt,name=url_link_deprecated,json=urlLinkDeprecated,proto3" json:"url_link_deprecated,omitempty"` // deprecated after Sep 31, 2021, remove compatible code after Dec 31, 2022
	UrlLink           *UrlLinkPayload `protobuf:"bytes,3,opt,name=url_link,json=urlLink,proto3" json:"url_link,omitempty"`
}

func (x *MessageSendUrlRequest) Reset() {
	*x = MessageSendUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendUrlRequest) ProtoMessage() {}

func (x *MessageSendUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendUrlRequest.ProtoReflect.Descriptor instead.
func (*MessageSendUrlRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{20}
}

func (x *MessageSendUrlRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// Deprecated: Do not use.
func (x *MessageSendUrlRequest) GetUrlLinkDeprecated() string {
	if x != nil {
		return x.UrlLinkDeprecated
	}
	return ""
}

func (x *MessageSendUrlRequest) GetUrlLink() *UrlLinkPayload {
	if x != nil {
		return x.UrlLink
	}
	return nil
}

type MessageSendUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// @deprecated:
	//  Huan(202109): Wrapper types must not be used going forward.
	//    https://cloud.google.com/apis/design/design_patterns#optional_primitive_fields
	//
	// Deprecated: Do not use.
	IdStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id_string_value_deprecated,json=idStringValueDeprecated,proto3" json:"id_string_value_deprecated,omitempty"` // Deprecated after Sep 31, 2021, will be removed after Dec 31, 2022
	Id                      string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageSendUrlResponse) Reset() {
	*x = MessageSendUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendUrlResponse) ProtoMessage() {}

func (x *MessageSendUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendUrlResponse.ProtoReflect.Descriptor instead.
func (*MessageSendUrlResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{21}
}

// Deprecated: Do not use.
func (x *MessageSendUrlResponse) GetIdStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.IdStringValueDeprecated
	}
	return nil
}

func (x *MessageSendUrlResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageRecallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageRecallRequest) Reset() {
	*x = MessageRecallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecallRequest) ProtoMessage() {}

func (x *MessageRecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecallRequest.ProtoReflect.Descriptor instead.
func (*MessageRecallRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{22}
}

func (x *MessageRecallRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageRecallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MessageRecallResponse) Reset() {
	*x = MessageRecallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecallResponse) ProtoMessage() {}

func (x *MessageRecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecallResponse.ProtoReflect.Descriptor instead.
func (*MessageRecallResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{23}
}

func (x *MessageRecallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MessageForwardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId      string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
}

func (x *MessageForwardRequest) Reset() {
	*x = MessageForwardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageForwardRequest) ProtoMessage() {}

func (x *MessageForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageForwardRequest.ProtoReflect.Descriptor instead.
func (*MessageForwardRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{24}
}

func (x *MessageForwardRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageForwardRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type MessageForwardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// @deprecated: use payload instead.
	//  Huan(202109): Wrapper types must not be used going forward.
	//    https://cloud.google.com/apis/design/design_patterns#optional_primitive_fields
	//
	// Deprecated: Do not use.
	IdStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id_string_value_deprecated,json=idStringValueDeprecated,proto3" json:"id_string_value_deprecated,omitempty"` // Deprecated after Sep 31, 2021, will be removed after Dec 31, 2022
	Id                      string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageForwardResponse) Reset() {
	*x = MessageForwardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageForwardResponse) ProtoMessage() {}

func (x *MessageForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageForwardResponse.ProtoReflect.Descriptor instead.
func (*MessageForwardResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{25}
}

// Deprecated: Do not use.
func (x *MessageForwardResponse) GetIdStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.IdStringValueDeprecated
	}
	return nil
}

func (x *MessageForwardResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageLocationRequest) Reset() {
	*x = MessageLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageLocationRequest) ProtoMessage() {}

func (x *MessageLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageLocationRequest.ProtoReflect.Descriptor instead.
func (*MessageLocationRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{26}
}

func (x *MessageLocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *LocationPayload `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *MessageLocationResponse) Reset() {
	*x = MessageLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageLocationResponse) ProtoMessage() {}

func (x *MessageLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageLocationResponse.ProtoReflect.Descriptor instead.
func (*MessageLocationResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{27}
}

func (x *MessageLocationResponse) GetLocation() *LocationPayload {
	if x != nil {
		return x.Location
	}
	return nil
}

type MessageSendLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string           `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Location       *LocationPayload `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *MessageSendLocationRequest) Reset() {
	*x = MessageSendLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendLocationRequest) ProtoMessage() {}

func (x *MessageSendLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendLocationRequest.ProtoReflect.Descriptor instead.
func (*MessageSendLocationRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{28}
}

func (x *MessageSendLocationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageSendLocationRequest) GetLocation() *LocationPayload {
	if x != nil {
		return x.Location
	}
	return nil
}

type MessageSendLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// Huan(202110): we will not use wrappers any more by following the Google Style Guide:
	//  If not using optional would add complexity or ambiguity, then use optional primitive fields,
	//  Wrapper types must not be used going forward.
	//  — Optional Primitive Fields (https://cloud.google.com/apis/design/design_patterns.md#optional-primitive-fields)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageSendLocationResponse) Reset() {
	*x = MessageSendLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_message_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendLocationResponse) ProtoMessage() {}

func (x *MessageSendLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_message_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendLocationResponse.ProtoReflect.Descriptor instead.
func (*MessageSendLocationResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_message_proto_rawDescGZIP(), []int{29}
}

func (x *MessageSendLocationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_wechaty_puppet_message_proto protoreflect.FileDescriptor

var file_wechaty_puppet_message_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2f, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1a, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2f, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x2f,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x77, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x79, 0x2f, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x2f, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x77, 0x65, 0x63, 0x68,
	0x61, 0x74, 0x79, 0x2f, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x2d,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x77,
	0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2f, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x2f, 0x75, 0x72,
	0x6c, 0x2d, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x15,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xf7, 0x02, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x35, 0x0a, 0x14, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x64, 0x65,
	0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02,
	0x18, 0x01, 0x52, 0x13, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x70,
	0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e,
	0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x6c, 0x6b,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x6c,
	0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x09,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73,
	0x12, 0x3d, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x54, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x70,
	0x75, 0x70, 0x70, 0x65, 0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x31, 0x0a, 0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x6f, 0x78, 0x22, 0x27, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x28, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x30, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65,
	0x42, 0x6f, 0x78, 0x22, 0x2b, 0x0a, 0x19, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x69,
	0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x9f, 0x01, 0x0a, 0x1a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x69, 0x6e, 0x69,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3a, 0x0a, 0x17, 0x6d, 0x69, 0x6e, 0x69, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f,
	0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x02, 0x18, 0x01, 0x52, 0x15, 0x6d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x45, 0x0a, 0x0c, 0x6d,
	0x69, 0x6e, 0x69, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x70, 0x75, 0x70, 0x70,
	0x65, 0x74, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x22, 0x23, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x13, 0x75, 0x72, 0x6c, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x64, 0x65, 0x70, 0x72, 0x65,
	0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x02, 0x18, 0x01, 0x52,
	0x11, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x39, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x70,
	0x75, 0x70, 0x70, 0x65, 0x74, 0x2e, 0x55, 0x72, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x63, 0x0a,
	0x19, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x1a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65,
	0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5d, 0x0a, 0x1a, 0x69, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x02, 0x18, 0x01, 0x52, 0x17, 0x69, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x5c, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x62, 0x6f, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x6f, 0x78, 0x22, 0x88,
	0x01, 0x0a, 0x17, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x1a, 0x69, 0x64,
	0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x64, 0x65,
	0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x02, 0x18, 0x01,
	0x52, 0x17, 0x69, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44,
	0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x7a, 0x0a, 0x16, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x17, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5d, 0x0a, 0x1a, 0x69, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x02, 0x18, 0x01, 0x52, 0x17, 0x69, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0xcb, 0x01, 0x0a, 0x1d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x17, 0x6d,
	0x69, 0x6e, 0x69, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x64, 0x65, 0x70, 0x72,
	0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x02, 0x18, 0x01,
	0x52, 0x15, 0x6d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x44, 0x65, 0x70,
	0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x45, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x69, 0x5f,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x2e, 0x4d,
	0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x22, 0x8f,
	0x01, 0x0a, 0x1e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x69,
	0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5d, 0x0a, 0x1a, 0x69, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x02, 0x18, 0x01, 0x52, 0x17, 0x69, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0xaf, 0x01, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x13, 0x75, 0x72, 0x6c, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f,
	0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x02, 0x18, 0x01, 0x52, 0x11, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x65, 0x70,
	0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x39, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x6c,
	0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x65, 0x63, 0x68,
	0x61, 0x74, 0x79, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x2e, 0x55, 0x72, 0x6c, 0x4c, 0x69,
	0x6e, 0x6b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69,
	0x6e, 0x6b, 0x22, 0x87, 0x01, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65,
	0x6e, 0x64, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a,
	0x1a, 0x69, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42,
	0x02, 0x18, 0x01, 0x52, 0x17, 0x69, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x5f, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12,
	0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x16, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x1a, 0x69, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x02, 0x18, 0x01, 0x52, 0x17, 0x69, 0x64, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x28, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x56, 0x0a, 0x17,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x77, 0x65, 0x63, 0x68,
	0x61, 0x74, 0x79, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x82, 0x01, 0x0a, 0x1a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x1b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x2a, 0xa0, 0x03, 0x0a, 0x0b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x4d, 0x45, 0x53, 0x53,
	0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x54, 0x54, 0x41, 0x43, 0x48, 0x4d, 0x45, 0x4e,
	0x54, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x4d,
	0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x54,
	0x41, 0x43, 0x54, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x4d, 0x4f, 0x54, 0x49, 0x43, 0x4f, 0x4e, 0x10, 0x04,
	0x12, 0x16, 0x0a, 0x12, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x05, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x45, 0x53, 0x53,
	0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x10, 0x06, 0x12,
	0x16, 0x0a, 0x12, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x07, 0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x48, 0x49, 0x53,
	0x54, 0x4f, 0x52, 0x59, 0x10, 0x08, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x09, 0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4d, 0x49, 0x4e, 0x49, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x41, 0x4d, 0x10, 0x0a,
	0x12, 0x19, 0x0a, 0x15, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x10, 0x0b, 0x12, 0x1d, 0x0a, 0x19, 0x4d,
	0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x44, 0x5f,
	0x45, 0x4e, 0x56, 0x45, 0x4c, 0x4f, 0x50, 0x45, 0x10, 0x0c, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x45,
	0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x43, 0x41, 0x4c,
	0x4c, 0x45, 0x44, 0x10, 0x0d, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x52, 0x4c, 0x10, 0x0e, 0x42, 0x67, 0x0a, 0x1d, 0x69,
	0x6f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x5a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79,
	0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79,
	0x2f, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0xaa, 0x02, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x75,
	0x70, 0x70, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wechaty_puppet_message_proto_rawDescOnce sync.Once
	file_wechaty_puppet_message_proto_rawDescData = file_wechaty_puppet_message_proto_rawDesc
)

func file_wechaty_puppet_message_proto_rawDescGZIP() []byte {
	file_wechaty_puppet_message_proto_rawDescOnce.Do(func() {
		file_wechaty_puppet_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_wechaty_puppet_message_proto_rawDescData)
	})
	return file_wechaty_puppet_message_proto_rawDescData
}

var file_wechaty_puppet_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wechaty_puppet_message_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_wechaty_puppet_message_proto_goTypes = []interface{}{
	(MessageType)(0),                       // 0: wechaty.puppet.MessageType
	(*MessagePayloadRequest)(nil),          // 1: wechaty.puppet.MessagePayloadRequest
	(*MessagePayloadResponse)(nil),         // 2: wechaty.puppet.MessagePayloadResponse
	(*MessageImageRequest)(nil),            // 3: wechaty.puppet.MessageImageRequest
	(*MessageImageResponse)(nil),           // 4: wechaty.puppet.MessageImageResponse
	(*MessageContactRequest)(nil),          // 5: wechaty.puppet.MessageContactRequest
	(*MessageContactResponse)(nil),         // 6: wechaty.puppet.MessageContactResponse
	(*MessageFileRequest)(nil),             // 7: wechaty.puppet.MessageFileRequest
	(*MessageFileResponse)(nil),            // 8: wechaty.puppet.MessageFileResponse
	(*MessageMiniProgramRequest)(nil),      // 9: wechaty.puppet.MessageMiniProgramRequest
	(*MessageMiniProgramResponse)(nil),     // 10: wechaty.puppet.MessageMiniProgramResponse
	(*MessageUrlRequest)(nil),              // 11: wechaty.puppet.MessageUrlRequest
	(*MessageUrlResponse)(nil),             // 12: wechaty.puppet.MessageUrlResponse
	(*MessageSendContactRequest)(nil),      // 13: wechaty.puppet.MessageSendContactRequest
	(*MessageSendContactResponse)(nil),     // 14: wechaty.puppet.MessageSendContactResponse
	(*MessageSendFileRequest)(nil),         // 15: wechaty.puppet.MessageSendFileRequest
	(*MessageSendFileResponse)(nil),        // 16: wechaty.puppet.MessageSendFileResponse
	(*MessageSendTextRequest)(nil),         // 17: wechaty.puppet.MessageSendTextRequest
	(*MessageSendTextResponse)(nil),        // 18: wechaty.puppet.MessageSendTextResponse
	(*MessageSendMiniProgramRequest)(nil),  // 19: wechaty.puppet.MessageSendMiniProgramRequest
	(*MessageSendMiniProgramResponse)(nil), // 20: wechaty.puppet.MessageSendMiniProgramResponse
	(*MessageSendUrlRequest)(nil),          // 21: wechaty.puppet.MessageSendUrlRequest
	(*MessageSendUrlResponse)(nil),         // 22: wechaty.puppet.MessageSendUrlResponse
	(*MessageRecallRequest)(nil),           // 23: wechaty.puppet.MessageRecallRequest
	(*MessageRecallResponse)(nil),          // 24: wechaty.puppet.MessageRecallResponse
	(*MessageForwardRequest)(nil),          // 25: wechaty.puppet.MessageForwardRequest
	(*MessageForwardResponse)(nil),         // 26: wechaty.puppet.MessageForwardResponse
	(*MessageLocationRequest)(nil),         // 27: wechaty.puppet.MessageLocationRequest
	(*MessageLocationResponse)(nil),        // 28: wechaty.puppet.MessageLocationResponse
	(*MessageSendLocationRequest)(nil),     // 29: wechaty.puppet.MessageSendLocationRequest
	(*MessageSendLocationResponse)(nil),    // 30: wechaty.puppet.MessageSendLocationResponse
	(*timestamppb.Timestamp)(nil),          // 31: google.protobuf.Timestamp
	(ImageType)(0),                         // 32: wechaty.puppet.ImageType
	(*MiniProgramPayload)(nil),             // 33: wechaty.puppet.MiniProgramPayload
	(*UrlLinkPayload)(nil),                 // 34: wechaty.puppet.UrlLinkPayload
	(*wrapperspb.StringValue)(nil),         // 35: google.protobuf.StringValue
	(*LocationPayload)(nil),                // 36: wechaty.puppet.LocationPayload
}
var file_wechaty_puppet_message_proto_depIdxs = []int32{
	0,  // 0: wechaty.puppet.MessagePayloadResponse.type:type_name -> wechaty.puppet.MessageType
	31, // 1: wechaty.puppet.MessagePayloadResponse.receive_time:type_name -> google.protobuf.Timestamp
	32, // 2: wechaty.puppet.MessageImageRequest.type:type_name -> wechaty.puppet.ImageType
	33, // 3: wechaty.puppet.MessageMiniProgramResponse.mini_program:type_name -> wechaty.puppet.MiniProgramPayload
	34, // 4: wechaty.puppet.MessageUrlResponse.url_link:type_name -> wechaty.puppet.UrlLinkPayload
	35, // 5: wechaty.puppet.MessageSendContactResponse.id_string_value_deprecated:type_name -> google.protobuf.StringValue
	35, // 6: wechaty.puppet.MessageSendFileResponse.id_string_value_deprecated:type_name -> google.protobuf.StringValue
	35, // 7: wechaty.puppet.MessageSendTextResponse.id_string_value_deprecated:type_name -> google.protobuf.StringValue
	33, // 8: wechaty.puppet.MessageSendMiniProgramRequest.mini_program:type_name -> wechaty.puppet.MiniProgramPayload
	35, // 9: wechaty.puppet.MessageSendMiniProgramResponse.id_string_value_deprecated:type_name -> google.protobuf.StringValue
	34, // 10: wechaty.puppet.MessageSendUrlRequest.url_link:type_name -> wechaty.puppet.UrlLinkPayload
	35, // 11: wechaty.puppet.MessageSendUrlResponse.id_string_value_deprecated:type_name -> google.protobuf.StringValue
	35, // 12: wechaty.puppet.MessageForwardResponse.id_string_value_deprecated:type_name -> google.protobuf.StringValue
	36, // 13: wechaty.puppet.MessageLocationResponse.location:type_name -> wechaty.puppet.LocationPayload
	36, // 14: wechaty.puppet.MessageSendLocationRequest.location:type_name -> wechaty.puppet.LocationPayload
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_wechaty_puppet_message_proto_init() }
func file_wechaty_puppet_message_proto_init() {
	if File_wechaty_puppet_message_proto != nil {
		return
	}
	file_wechaty_puppet_image_proto_init()
	file_wechaty_puppet_location_proto_init()
	file_wechaty_puppet_mini_program_proto_init()
	file_wechaty_puppet_url_link_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_wechaty_puppet_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePayloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePayloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageContactRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageContactResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageMiniProgramRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageMiniProgramResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendContactRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendContactResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendMiniProgramRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendMiniProgramResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRecallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRecallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageForwardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageForwardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_message_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wechaty_puppet_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wechaty_puppet_message_proto_goTypes,
		DependencyIndexes: file_wechaty_puppet_message_proto_depIdxs,
		EnumInfos:         file_wechaty_puppet_message_proto_enumTypes,
		MessageInfos:      file_wechaty_puppet_message_proto_msgTypes,
	}.Build()
	File_wechaty_puppet_message_proto = out.File
	file_wechaty_puppet_message_proto_rawDesc = nil
	file_wechaty_puppet_message_proto_goTypes = nil
	file_wechaty_puppet_message_proto_depIdxs = nil
}
