// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: wechaty/puppet/room-invitation.proto

package puppet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomInvitationPayloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//*
	// Huan(202002): `payload` should be removed.
	//  The puppet server should take the responsibilities
	//  for storing the unaccepted friend-request payload.
	//
	// @deprecated: use payload instead.
	//  Huan(202109): Wrapper types must not be used going forward.
	//    https://cloud.google.com/apis/design/design_patterns#optional_primitive_fields
	//
	// Deprecated: Do not use.
	PayloadStringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=payload_string_value_deprecated,json=payloadStringValueDeprecated,proto3" json:"payload_string_value_deprecated,omitempty"` // Deprecated: will be removed after Dec 31, 2022
	Payload                      string                  `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *RoomInvitationPayloadRequest) Reset() {
	*x = RoomInvitationPayloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_room_invitation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInvitationPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInvitationPayloadRequest) ProtoMessage() {}

func (x *RoomInvitationPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_room_invitation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInvitationPayloadRequest.ProtoReflect.Descriptor instead.
func (*RoomInvitationPayloadRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_room_invitation_proto_rawDescGZIP(), []int{0}
}

func (x *RoomInvitationPayloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Deprecated: Do not use.
func (x *RoomInvitationPayloadRequest) GetPayloadStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.PayloadStringValueDeprecated
	}
	return nil
}

func (x *RoomInvitationPayloadRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type RoomInvitationPayloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InviterId   string   `protobuf:"bytes,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	Topic       string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	MemberCount int32    `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	MemberIds   []string `protobuf:"bytes,5,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	//*
	// @deprecated will be removed after Dec 31, 2022
	//  Huan(202109): use receive_time(10) instead
	//
	// Deprecated: Do not use.
	TimestampUint64Deprecated uint64                 `protobuf:"varint,6,opt,name=timestamp_uint64_deprecated,json=timestampUint64Deprecated,proto3" json:"timestamp_uint64_deprecated,omitempty"` // Deprecated: will be removed after Dec 31, 2022
	Avatar                    string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Invitation                string                 `protobuf:"bytes,8,opt,name=invitation,proto3" json:"invitation,omitempty"`
	ReceiverId                string                 `protobuf:"bytes,9,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ReceiveTime               *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
}

func (x *RoomInvitationPayloadResponse) Reset() {
	*x = RoomInvitationPayloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_room_invitation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInvitationPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInvitationPayloadResponse) ProtoMessage() {}

func (x *RoomInvitationPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_room_invitation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInvitationPayloadResponse.ProtoReflect.Descriptor instead.
func (*RoomInvitationPayloadResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_room_invitation_proto_rawDescGZIP(), []int{1}
}

func (x *RoomInvitationPayloadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomInvitationPayloadResponse) GetInviterId() string {
	if x != nil {
		return x.InviterId
	}
	return ""
}

func (x *RoomInvitationPayloadResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RoomInvitationPayloadResponse) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *RoomInvitationPayloadResponse) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

// Deprecated: Do not use.
func (x *RoomInvitationPayloadResponse) GetTimestampUint64Deprecated() uint64 {
	if x != nil {
		return x.TimestampUint64Deprecated
	}
	return 0
}

func (x *RoomInvitationPayloadResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RoomInvitationPayloadResponse) GetInvitation() string {
	if x != nil {
		return x.Invitation
	}
	return ""
}

func (x *RoomInvitationPayloadResponse) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *RoomInvitationPayloadResponse) GetReceiveTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceiveTime
	}
	return nil
}

type RoomInvitationAcceptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RoomInvitationAcceptRequest) Reset() {
	*x = RoomInvitationAcceptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_room_invitation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInvitationAcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInvitationAcceptRequest) ProtoMessage() {}

func (x *RoomInvitationAcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_room_invitation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInvitationAcceptRequest.ProtoReflect.Descriptor instead.
func (*RoomInvitationAcceptRequest) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_room_invitation_proto_rawDescGZIP(), []int{2}
}

func (x *RoomInvitationAcceptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RoomInvitationAcceptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoomInvitationAcceptResponse) Reset() {
	*x = RoomInvitationAcceptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wechaty_puppet_room_invitation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInvitationAcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInvitationAcceptResponse) ProtoMessage() {}

func (x *RoomInvitationAcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wechaty_puppet_room_invitation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInvitationAcceptResponse.ProtoReflect.Descriptor instead.
func (*RoomInvitationAcceptResponse) Descriptor() ([]byte, []int) {
	return file_wechaty_puppet_room_invitation_proto_rawDescGZIP(), []int{3}
}

var File_wechaty_puppet_room_invitation_proto protoreflect.FileDescriptor

var file_wechaty_puppet_room_invitation_proto_rawDesc = []byte{
	0x0a, 0x24, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2f, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74,
	0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e,
	0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x1c, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x67, 0x0a, 0x1f, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42,
	0x02, 0x18, 0x01, 0x52, 0x1c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x82, 0x03, 0x0a, 0x1d,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x49, 0x64, 0x73, 0x12, 0x42, 0x0a, 0x1b, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x5f, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x18, 0x01, 0x52, 0x19, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x44, 0x65,
	0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x2d, 0x0a, 0x1b, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x1e, 0x0a, 0x1c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x67, 0x0a, 0x1d, 0x69, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x77, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74,
	0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x79, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x79, 0x2f, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0xaa, 0x02, 0x1a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x79, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x75, 0x70, 0x70, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wechaty_puppet_room_invitation_proto_rawDescOnce sync.Once
	file_wechaty_puppet_room_invitation_proto_rawDescData = file_wechaty_puppet_room_invitation_proto_rawDesc
)

func file_wechaty_puppet_room_invitation_proto_rawDescGZIP() []byte {
	file_wechaty_puppet_room_invitation_proto_rawDescOnce.Do(func() {
		file_wechaty_puppet_room_invitation_proto_rawDescData = protoimpl.X.CompressGZIP(file_wechaty_puppet_room_invitation_proto_rawDescData)
	})
	return file_wechaty_puppet_room_invitation_proto_rawDescData
}

var file_wechaty_puppet_room_invitation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wechaty_puppet_room_invitation_proto_goTypes = []interface{}{
	(*RoomInvitationPayloadRequest)(nil),  // 0: wechaty.puppet.RoomInvitationPayloadRequest
	(*RoomInvitationPayloadResponse)(nil), // 1: wechaty.puppet.RoomInvitationPayloadResponse
	(*RoomInvitationAcceptRequest)(nil),   // 2: wechaty.puppet.RoomInvitationAcceptRequest
	(*RoomInvitationAcceptResponse)(nil),  // 3: wechaty.puppet.RoomInvitationAcceptResponse
	(*wrapperspb.StringValue)(nil),        // 4: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),         // 5: google.protobuf.Timestamp
}
var file_wechaty_puppet_room_invitation_proto_depIdxs = []int32{
	4, // 0: wechaty.puppet.RoomInvitationPayloadRequest.payload_string_value_deprecated:type_name -> google.protobuf.StringValue
	5, // 1: wechaty.puppet.RoomInvitationPayloadResponse.receive_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wechaty_puppet_room_invitation_proto_init() }
func file_wechaty_puppet_room_invitation_proto_init() {
	if File_wechaty_puppet_room_invitation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wechaty_puppet_room_invitation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInvitationPayloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_room_invitation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInvitationPayloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_room_invitation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInvitationAcceptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wechaty_puppet_room_invitation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInvitationAcceptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wechaty_puppet_room_invitation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wechaty_puppet_room_invitation_proto_goTypes,
		DependencyIndexes: file_wechaty_puppet_room_invitation_proto_depIdxs,
		MessageInfos:      file_wechaty_puppet_room_invitation_proto_msgTypes,
	}.Build()
	File_wechaty_puppet_room_invitation_proto = out.File
	file_wechaty_puppet_room_invitation_proto_rawDesc = nil
	file_wechaty_puppet_room_invitation_proto_goTypes = nil
	file_wechaty_puppet_room_invitation_proto_depIdxs = nil
}
