// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room_member.proto

package puppet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomMemberPayloadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId             string   `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomMemberPayloadRequest) Reset()         { *m = RoomMemberPayloadRequest{} }
func (m *RoomMemberPayloadRequest) String() string { return proto.CompactTextString(m) }
func (*RoomMemberPayloadRequest) ProtoMessage()    {}
func (*RoomMemberPayloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_63e6562082d7765e, []int{0}
}

func (m *RoomMemberPayloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMemberPayloadRequest.Unmarshal(m, b)
}
func (m *RoomMemberPayloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMemberPayloadRequest.Marshal(b, m, deterministic)
}
func (m *RoomMemberPayloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMemberPayloadRequest.Merge(m, src)
}
func (m *RoomMemberPayloadRequest) XXX_Size() int {
	return xxx_messageInfo_RoomMemberPayloadRequest.Size(m)
}
func (m *RoomMemberPayloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMemberPayloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMemberPayloadRequest proto.InternalMessageInfo

func (m *RoomMemberPayloadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomMemberPayloadRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

type RoomMemberPayloadResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomAlias            string   `protobuf:"bytes,2,opt,name=room_alias,json=roomAlias,proto3" json:"room_alias,omitempty"`
	InviterId            string   `protobuf:"bytes,3,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomMemberPayloadResponse) Reset()         { *m = RoomMemberPayloadResponse{} }
func (m *RoomMemberPayloadResponse) String() string { return proto.CompactTextString(m) }
func (*RoomMemberPayloadResponse) ProtoMessage()    {}
func (*RoomMemberPayloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_63e6562082d7765e, []int{1}
}

func (m *RoomMemberPayloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMemberPayloadResponse.Unmarshal(m, b)
}
func (m *RoomMemberPayloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMemberPayloadResponse.Marshal(b, m, deterministic)
}
func (m *RoomMemberPayloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMemberPayloadResponse.Merge(m, src)
}
func (m *RoomMemberPayloadResponse) XXX_Size() int {
	return xxx_messageInfo_RoomMemberPayloadResponse.Size(m)
}
func (m *RoomMemberPayloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMemberPayloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMemberPayloadResponse proto.InternalMessageInfo

func (m *RoomMemberPayloadResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomMemberPayloadResponse) GetRoomAlias() string {
	if m != nil {
		return m.RoomAlias
	}
	return ""
}

func (m *RoomMemberPayloadResponse) GetInviterId() string {
	if m != nil {
		return m.InviterId
	}
	return ""
}

func (m *RoomMemberPayloadResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *RoomMemberPayloadResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RoomMemberListRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomMemberListRequest) Reset()         { *m = RoomMemberListRequest{} }
func (m *RoomMemberListRequest) String() string { return proto.CompactTextString(m) }
func (*RoomMemberListRequest) ProtoMessage()    {}
func (*RoomMemberListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_63e6562082d7765e, []int{2}
}

func (m *RoomMemberListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMemberListRequest.Unmarshal(m, b)
}
func (m *RoomMemberListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMemberListRequest.Marshal(b, m, deterministic)
}
func (m *RoomMemberListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMemberListRequest.Merge(m, src)
}
func (m *RoomMemberListRequest) XXX_Size() int {
	return xxx_messageInfo_RoomMemberListRequest.Size(m)
}
func (m *RoomMemberListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMemberListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMemberListRequest proto.InternalMessageInfo

func (m *RoomMemberListRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoomMemberListResponse struct {
	MemberIds            []string `protobuf:"bytes,1,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomMemberListResponse) Reset()         { *m = RoomMemberListResponse{} }
func (m *RoomMemberListResponse) String() string { return proto.CompactTextString(m) }
func (*RoomMemberListResponse) ProtoMessage()    {}
func (*RoomMemberListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_63e6562082d7765e, []int{3}
}

func (m *RoomMemberListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMemberListResponse.Unmarshal(m, b)
}
func (m *RoomMemberListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMemberListResponse.Marshal(b, m, deterministic)
}
func (m *RoomMemberListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMemberListResponse.Merge(m, src)
}
func (m *RoomMemberListResponse) XXX_Size() int {
	return xxx_messageInfo_RoomMemberListResponse.Size(m)
}
func (m *RoomMemberListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMemberListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMemberListResponse proto.InternalMessageInfo

func (m *RoomMemberListResponse) GetMemberIds() []string {
	if m != nil {
		return m.MemberIds
	}
	return nil
}

func init() {
	proto.RegisterType((*RoomMemberPayloadRequest)(nil), "wechaty.puppet.RoomMemberPayloadRequest")
	proto.RegisterType((*RoomMemberPayloadResponse)(nil), "wechaty.puppet.RoomMemberPayloadResponse")
	proto.RegisterType((*RoomMemberListRequest)(nil), "wechaty.puppet.RoomMemberListRequest")
	proto.RegisterType((*RoomMemberListResponse)(nil), "wechaty.puppet.RoomMemberListResponse")
}

func init() {
	proto.RegisterFile("room_member.proto", fileDescriptor_63e6562082d7765e)
}

var fileDescriptor_63e6562082d7765e = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0x5a, 0x8b, 0x99, 0x43, 0xc1, 0x05, 0xcb, 0x8a, 0x14, 0x4a, 0x2e, 0x2a, 0x62,
	0x7a, 0xf0, 0xe0, 0x59, 0x2f, 0x52, 0x50, 0x90, 0x1c, 0xbd, 0x94, 0x49, 0x76, 0x49, 0x17, 0xba,
	0x99, 0x35, 0xbb, 0xa9, 0xf4, 0x83, 0xf8, 0x7d, 0x25, 0xbb, 0x6b, 0x05, 0xff, 0xdc, 0x32, 0xbf,
	0x37, 0xbc, 0xbc, 0x37, 0x0b, 0x27, 0x1d, 0x91, 0x5e, 0x6b, 0xa9, 0x2b, 0xd9, 0x15, 0xa6, 0x23,
	0x47, 0x6c, 0xfa, 0x2e, 0xeb, 0x0d, 0xba, 0x7d, 0x61, 0x7a, 0x63, 0xa4, 0xcb, 0x1f, 0x81, 0x97,
	0x44, 0xfa, 0xd9, 0xef, 0xbc, 0xe0, 0x7e, 0x4b, 0x28, 0x4a, 0xf9, 0xd6, 0x4b, 0xeb, 0xd8, 0x14,
	0x52, 0x25, 0x78, 0xb2, 0x48, 0x2e, 0xb3, 0x32, 0x55, 0x82, 0x9d, 0x43, 0x16, 0xbc, 0xd6, 0x4a,
	0xf0, 0xd4, 0xe3, 0xe3, 0x00, 0x56, 0x22, 0xff, 0x48, 0xe0, 0xec, 0x0f, 0x27, 0x6b, 0xa8, 0xb5,
	0xf2, 0x97, 0xd5, 0x1c, 0xc0, 0x67, 0xc3, 0xad, 0x42, 0x1b, 0xbd, 0xb2, 0x81, 0xdc, 0x0f, 0x60,
	0x90, 0x55, 0xbb, 0x53, 0x2e, 0xfc, 0x6a, 0x14, 0xe4, 0x48, 0x56, 0x82, 0xcd, 0x60, 0x82, 0x3b,
	0x74, 0xd8, 0xf1, 0xb1, 0x97, 0xe2, 0xc4, 0x18, 0x8c, 0x5b, 0xd4, 0x92, 0x1f, 0x79, 0xea, 0xbf,
	0xf3, 0x0b, 0x38, 0xfd, 0x8e, 0xf5, 0xa4, 0xac, 0xfb, 0xa7, 0x5d, 0x7e, 0x07, 0xb3, 0x9f, 0x8b,
	0x31, 0xfc, 0x1c, 0xe0, 0xd0, 0xdb, 0xf2, 0x64, 0x31, 0x1a, 0xd2, 0x7c, 0x15, 0xb7, 0x0f, 0xd7,
	0xaf, 0x57, 0x8d, 0x72, 0x9b, 0xbe, 0x2a, 0x6a, 0xd2, 0xcb, 0x78, 0xdf, 0x65, 0x43, 0x37, 0x4d,
	0x67, 0xea, 0xc3, 0x1c, 0xee, 0x5d, 0x4d, 0xfc, 0x33, 0xdc, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x78, 0x56, 0xe5, 0xa5, 0x9b, 0x01, 0x00, 0x00,
}
